trigger:
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master

variables:
  pythonVersion: 3.7
  venvDirectory: $(System.DefaultWorkingDirectory)/venv

jobs:
- job: test
  displayName: test
  pool:
    vmImage: windows-2019
  steps:
  - task: UsePythonVersion@0
    displayName: Use Python $(pythonVersion)
    inputs:
      versionSpec: $(pythonVersion)
  - script: python -m pip install -r requirements/ci.txt
    displayName: install python requirements/ci.txt
  - script: python -m virtualenv $(venvDirectory)
    displayName: setup virtual environment
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      python -m pip list
    displayName: pip list before
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      python -m pip install -r requirements/test.txt
    displayName: install requirements/test.txt
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      python -m pip install --editable .
    displayName: install gravitybee
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      python -m pip install --editable tests/gbtestapp
    displayName: install tests/gbtestapp
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      python -m pip install --editable tests/testapp2
    displayName: install tests/testapp2
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      python -m pip list
    displayName: pip list after
  - script: |
      call $(venvDirectory)/Scripts/activate.bat
      pytest
    displayName: pytest
